dist: trusty


services:
  - docker

env:
  global:
    - VERSION=0.0.1
    - DOCKER_IMAGE_API=agregorc/protein-rna-interactions-api:$VERSION
    - DOCKER_IMAGE_WEB_APP=agregorc/protein-rna-interactions-web-app:$VERSION

script:
  - docker build -t $DOCKER_IMAGE_WEB_APP src/web/vue-app

  # Build api image from flask dockerfile but in root directory
  - docker build -t $DOCKER_IMAGE_API -f src/web/flask/Dockerfile .

after_success:
  - echo "after_success command"
