
DATA_PATH = 'data/'
SAVED_GRAPHS_PATH = DATA_PATH + 'preprocessed_data/'
SAVED_GRAPHS_PATH_DEFAULT_FILE = SAVED_GRAPHS_PATH + 'graph_data.bin'
PDB_PATH = DATA_PATH + 'pdbs/'

ATOM_DGL_ID = 'my_dgl_id'
LABEL_ATTRIBUTE_NAME = 'my_label'
LABEL_ATOM_DISTANCE = 4.2

LABEL_NODE_NAME = 'label'
LABEL_POSITIVE_COLOR = 'r'
LABEL_NEGATIVE_COLOR = 'b'
LABEL_POSITIVE = 1
LABEL_NEGATIVE = 0

NODE_FEATURES_NAME = 'features'
NODE_FEATURES_NUM = 6
EDGE_FEATURE_NAME = 'relative_position'
EDGE_FEATURE_NUM = 4
