version: "3.9"
services:
  api:
    image: agregorc/protein-rna-interactions-api:0.0.2
    ports:
      - "5004:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
      NUM_PROCESSES: 2
      ADMIN_PASS: $ADMIN_PASS
      PYTHONUNBUFFERED: 1
  data-updater:
    image: agregorc/protein-rna-interactions-data-updater:0.0.2
    volumes:
      - .:/app
    environment:
      NUM_PROCESSES: 2
      ADMIN_PASS: $ADMIN_PASS
      PYTHONUNBUFFERED: 1
  web-app:
    image: agregorc/protein-rna-interactions-web-app:0.0.2
    ports: 
      - "8080:8080"
    environment:
      VUE_APP_API_URL: http://193.2.72.56:5004/api/
