FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04

# Install some basic utilities
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
 && rm -rf /var/lib/apt/lists/*

# install anaconda
RUN apt-get update
RUN apt-get install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git mercurial subversion && \
        apt-get clean
RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh -O ~/anaconda.sh && \
        /bin/bash ~/anaconda.sh -b -p /opt/conda && \
        rm ~/anaconda.sh && \
        ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
        echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
        find /opt/conda/ -follow -type f -name '*.a' -delete && \
        find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
        /opt/conda/bin/conda clean -afy


# set path to conda
ENV PATH /opt/conda/bin:$PATH


# install from requirements.txt
RUN conda update conda \
    && conda install --file requirements.txt -c pytorch -c dglteam -c conda-forge


# Create a working directory
RUN mkdir /app
WORKDIR /app

# Copy the code
COPY . .

# Change workdir to flask directory
WORKDIR /app/src/web/flask

# Run the API server using uwsgi
CMD ["uwsgi --ini uwsgi.ini"]